sudo: required
services:
  - docker

before_install:
  - docker build -t jacobgoodwin0/docker-react-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true jacobgoodwin0/docker-react-demo npm run test
